export const topics = [
  {
    header: "Introudction",
    body: [
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
    ],
  },
  {
    header: "Advnce",
    body: [
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
      "Chapter One",
    ],
  },
];
